name: Linux

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v4
    - name: use stable toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: install dependencies
      run: sudo apt-get install -y libfontconfig1-dev
    - name: build
      run: cargo build --verbose

