name: MacOS
run-name: "${{ github.head_ref }} ${{ github.sha }} by @${{ github.actor }}"

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v4
    - name: use stable toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: build
      run: cargo build --verbose

